---
title: "HW4_Mengyi Dong"
author: "MengyiDong"
date: "9/15/2020"
output: html_document
---
```{r}
## Obtain data file pheno.txt.
getwd()
setwd("/Users/Mengyi/Box/CPSC441 R programming/class_notes/HW4")
phenodata <- read.delim("pheno.txt", header = TRUE, sep = " ")
names(phenodata)
```

```{r}
## 1) How many unique observations are there in the “GENO” variable?
length(unique(phenodata$GENO))
```
```{r}
## 2) Save as a text file a subset of the pheno data set containing only range 1.
sub_phenodata <- phenodata[phenodata$range == 1,]
write.table(x=sub_phenodata, file="sub_phenodata.txt")
sub_phenodata
```

```{r}
## 3) The range (minimum and maximum value) of the “Y”, “M”, and “h4” variables.
range(phenodata$Y[!is.na(phenodata$Y)])
range(phenodata$M[!is.na(phenodata$M)])
range(phenodata$h4[!is.na(phenodata$h4)])
```
```{r}
## 4) What row contains the maximum value of “h4”?
h4 <- phenodata$h4
which.max((h4[!is.na(h4)]))
```
```{r}
## 5) Create a loop that prints the mean of the variables “Y”, “M”, “h1”, “h2”, “h3”, and “h4” (it must be done using a loop, e.g., for, while, or repeat).
## Y, M, h1, h2, h3, h4 are columns number 7-12. Thus,
i <- 7
repeat{
  x <- mean(phenodata[,i][!is.na(phenodata[,i])])
  print(x)
  i = i+1
  if (i>12) {break}
}

```

```{r}
## 6) Create a dataset called pheno2 and replace the values of “Y” that are smaller than 2 by 0.
pheno2 <- phenodata 
pheno2$Y[pheno2$Y < 2] <-0 
range(pheno2$Y[!is.na(pheno2$Y)])
pheno2
```

