---
title: "Hannah Demler HW6"
author: "Hannah Demler"
date: "9/30/2020"
output: html_document
---

**1**  
**Using flights data from nycflights13... Obtain the range, mean, and median of the variable "distance"**  
```{r}
install.packages("nycflights13")
flights<-nycflights13::flights

mean(flights$distance)
median(flights$distance)
range(flights$distance)
```
**2**  
**Combine the airlines with the flights data in a single file**
```{r}
airlines<- nycflights13::airlines
new_data<-full_join(flights,airlines)
```

**3**  
**Save a file including only American Airlines ordered by arr_delay**
```{r}
american<- new_data %>%
  filter(carrier=="AA") %>%
  arrange(desc(arr_delay))
```

**4**  
**Create boxplots of dep_delay by carrier**
```{r}
ggplot(new_data,aes(x = carrier, y = dep_delay))+
  geom_boxplot() +
  xlab("Carrier") + ylab("Departure Delay")+ 
  ggtitle("Departure Delays Among Aircraft Carriers")
```

**5**  
**Find the month with the highest arr_delay and show in a graph**
```{r}
#The observation of the single highest arr_delay is observation 7073 in month 1
which.max(new_data$arr_delay)

#However, the month with the highest mean arr_delay is month 7
data1<-na.omit(new_data)
group_by(data1, month) %>% summarize(arr_delay = mean(arr_delay))

#I created a graph of the mean arr_delay by month, showing that month 7 has the highest mean arr_delay
graphdata<-select(data1, month, arr_delay)

graphdata1<-aggregate(graphdata[,2],list(data1$month),mean)

ggplot(data=graphdata1, aes(x=Group.1 ,y=arr_delay)) + geom_bar(stat="identity")+
xlab("Month") + ylab("Mean Arrival Delay")+ scale_x_discrete(name="Month",limits=c("1","2","3","4","5","6","7","8","9","10","11","12"))+
  ggtitle("Mean Arrival Delay for each Month") 
```

