---
title: "Leo_dagostino_HW6"
author: "Leo D'Agostino"
date: "10/5/2020"
output: html_document
---

```{r}
install.packages("nycflights13")
library(nycflights13)
data(flights)
library(dplyr)
library(ggplot2)
```

Question 1
```{r}
mean(flights$distance)
median(flights$distance)
range(flights$distance)
```

Question 2
```{r}
airlines_flights <- merge(flights, airlines)
airlines_flights
```

Question 3
```{r}
aa_flights <- airlines_flights %>%
  filter(carrier == "AA") %>%
  arrange(arr_delay)

write.csv(aa_flights, "american_airlines.csv")
```

Question 4
```{r}
dep_delay <- ggplot(airlines_flights, aes(x = carrier, y = dep_delay)) + 
  geom_boxplot(na.rm = T) +
  labs(x = "carrier", y = "departure delay") +
  ggtitle("departure delay by carrier")
dep_delay
```

Question 5
```{r}
max_month <- ggplot(airlines_flights, aes(x = factor(month), y = arr_delay)) +
  geom_boxplot(outlier.colour="orange" , na.rm = T) +
  labs(x = "month", y = "arr delay") +
  ggtitle("arr delay by month")
max_month

max(airlines_flights$arr_delay, na.rm = T)

#month 1 has the highest arr_delay value, month 1 = january. highest value was checked with max function
```

















