---
title: "HW6_Mengyi Dong"
author: "MengyiDong"
date: "10/1/2020"
output: html_document
---

```{r}
## Load packages and data file.
library(tidyverse)
library(nycflights13)
flights1 <- nycflights13::flights
```

```{r}
## 1- obtain the range, mean, and median of the variable “distance”.
range(flights1$distance)
mean(flights1$distance)
median(flights1$distance)
```

```{r}
## 2- combine the airlines (also available from nycflights13) with the flights data in a single file.
flight_new <- full_join(airlines,flights, by= "carrier")
write.table(flight_new, file = "Flight_detailed.txt")
```

```{r}
## 3- save a file including only American Airlines (Carrier = AA) ordered by arr_delay.
AA <- flight_new %>%
  filter(flight_new$carrier == "AA") %>%
  arrange(arr_delay)
write.table(AA, file = "American Airlines.txt")
```


```{r}
## 4- create boxplots of dep_delay by carrier (one boxplot for each carrier).
dep_delay <- ggplot(flight_new,aes(x = carrier, y = dep_delay))+
  geom_boxplot()+
  xlab("Carrier") + ylab("Departure Delay")+
  ggtitle("Departure Delay by Carrier")
dep_delay
```

```{r}
## 5- find what is the month with the highest arr_delay. Show this in a graph.
Average_arr_delay <- select(flight_new, arr_delay, month) %>%
  na.omit()%>%
  group_by(month)%>% 
  summarize(mean_arr_delay = mean(arr_delay))
which.max(Average_arr_delay$mean_arr_delay)
## Visualize the data using histogram
arrival_delay <- ggplot(Average_arr_delay, aes(x = month, y = mean_arr_delay))+
  geom_histogram(stat = "identity")+
  scale_x_discrete(limits = c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sept", "Oct", "Nov", "Dec")) +
  ggtitle("Average Arrival Delay by Month") + 
  xlab("Month") + 
  ylab("Average Arrival Delay")
arrival_delay
```


