---
title: "Andrea.DestHW6"
author: "Andrea Dest"
date: "9/29/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

__Question 1__
```{r}
##get range, mean, and median from "distance"
library(nycflights13)
library(tidyverse)
flights <- nycflights13::flights

flights %>%
  summarise(mean(distance), median(distance), range(distance))
```

__Question 2__
```{r}
##combine airlines data and flights data in one file
airlines <- nycflights13::airlines
flights_with_airlines <- merge(flights, airlines, all.x = T)

```

__Question 3__
```{r}
##save file with American Airlines data organized by arr-delay
AA_flights <- flights_with_airlines %>%
  filter(carrier == "AA") %>%
  arrange(arr_delay)

  write_csv(AA_flights, "AA_flights.csv")
```

__Question 4__
```{r}
##create boxplot with dep_delay, by carrier 
library(ggplot2)
print(ggplot(flights) + geom_point(aes(carrier,dep_delay))+ ggtitle("Departure Delay by Carrier"))
```

__Question 5__
```{r}
#add data to find total delay
flights2 <- mutate(flights, total_delay = flights$dep_delay, flights$arr_delay)
#find max delay in data
max_delay <- max(flights2$total_delay, na.rm = T)
#use ggplot to plot delay data and show max delay 
library(ggplot2)
print(ggplot(flights2) + geom_point(aes(month, total_delay), color=ifelse(flights2$total_delay==max_delay, 'red', 'black'))+ ggtitle("Delay Totals by Month"))
```

